export default [
  { char: 'A' },
  { char: 'B' },
  { char: 'C' },
  { char: 'D' },
  { char: 'E' },
  { char: 'F' },
  { char: 'G' },
  { char: 'H' },
  { char: 'I' },
  { char: 'J' },
  { char: 'K' },
  { char: 'L' },
  { char: 'M' },
  { char: 'N' },
  { char: 'O' },
  { char: 'P' },
  { char: 'Q' },
  { char: 'R' },
  { char: 'S' },
  { char: 'T' },
  { char: 'U' },
  { char: 'V' },
  { char: 'W' },
  { char: 'X' },
  { char: 'Y' },
  { char: 'Z' },
  { char: '0-9', last: true }
]
